In [1]:
import pandas as pd

df = pd.read_csv('PowerGrid_Utility_Intelligence.csv')
df.head()

,asset_id,asset_type,asset_age_years,substation_region,manufacturer,power_load_mw,load_utilization_pct,voltage_fluctuation_pct,frequency_deviation_hz,transformer_temperature_c,...,rainfall_mm,storm_risk_index,customers_served,estimated_revenue_loss,regulatory_penalty_cost,legacy_asset_code,grid_cluster_id,monitoring_batch_id,administrative_reference,grid_failure_flag
0,100000,Transmission Line,39,Central,ABB,282.834500,81.260178,1.411161,-0.369930,66.340916,...,19.456628,66.896392,39815,586776.070558,340322.796883,139462,36,1711,810874,0
1,100001,Switchgear,29,Central,Schneider,113.757291,70.553974,7.717056,0.374570,76.476670,...,13.164766,39.487362,47370,801405.346049,279753.231580,336586,37,5380,257421,0
2,100002,Transmission Line,15,North,ABB,77.585841,39.118728,11.181348,0.024103,68.774685,...,32.955459,58.143304,25676,251440.743424,355793.399422,964465,36,7231,428171,1
3,100003,Transmission Line,8,South,Schneider,84.918625,96.994550,4.052007,-0.162436,81.823217,...,38.933280,31.747796,46451,942296.677282,27470.270655,234440,36,8277,336795,0
4,100004,Circuit Breaker,21,South,Schneider,101.442960,84.967689,5.130973,-0.170869,91.874408,...,43.279001,88.483389,21706,20110.477241,464487.465960,800776,4,6848,491835,1

In [2]:
df.groupby('asset_type').size()

asset_type
Circuit Breaker       9779
Substation            9662
Switchgear            9805
TRANSFORMER            715
Transformer          10253
Transmission Line     9646
transformer            640
dtype: int64

In [12]:
# clean the data - change TRANSFORMER and transformer to Transformer in the 'asset_type' column.
df['asset_type'] = df['asset_type'].replace({'TRANSFORMER': 'Transformer', 'transformer': 'Transformer'})
df.groupby('asset_type').size()

df.groupby(['substation_region', 'asset_type']).size()

substation_region  asset_type
Central            Circuit Breaker      1951
                   Substation           1894
                   Switchgear           1908
                   Transformer          2348
                   Transmission Line    1991
East               Circuit Breaker      1996
                   Substation           1959
                   Switchgear           2014
                   Transformer          2329
                   Transmission Line    1936
North              Circuit Breaker      2011
                   Substation           1964
                   Switchgear           1929
                   Transformer          2285
                   Transmission Line    1860
South              Circuit Breaker      1935
                   Substation           1952
                   Switchgear           1975
                   Transformer          2353
                   Transmission Line    1898
West               Circuit Breaker      1886
                   Substation           1893
                   Switchgear           1979
                   Transformer          2293
                   Transmission Line    1961
dtype: int64

In [10]:
# show all column data for asset_type = 'Transformer' and substation_region = 'North'
df[(df['asset_type'] == 'Transformer') & (df['substation_region'] == 'North')]

,asset_id,asset_type,asset_age_years,substation_region,manufacturer,power_load_mw,load_utilization_pct,voltage_fluctuation_pct,frequency_deviation_hz,transformer_temperature_c,...,rainfall_mm,storm_risk_index,customers_served,estimated_revenue_loss,regulatory_penalty_cost,legacy_asset_code,grid_cluster_id,monitoring_batch_id,administrative_reference,grid_failure_flag
6,100006,Transformer,19,North,GE,24.296135,66.411446,3.014399,-0.435844,44.241815,...,24.708504,10.976016,50575,852924.634858,264223.918831,457093,41,9871,753448,1
21,100021,Transformer,33,North,ABB,104.062495,61.161280,14.040740,0.067682,67.845371,...,65.884903,79.714194,91505,419699.985057,387117.626058,166107,7,9720,520115,1
49,100049,Transformer,36,North,ABB,93.725320,59.714063,1.022527,0.407803,61.766329,...,42.393218,55.875311,31067,637420.628667,216716.161169,134687,4,2255,242775,0
82,100082,Transformer,11,North,Schneider,124.717814,92.269759,0.457128,0.037259,58.291318,...,43.767124,11.171735,11429,89254.671304,53033.177326,425202,17,4598,776787,1
103,100103,Transformer,35,North,ABB,2.805928,48.898519,11.174533,0.236891,78.045479,...,31.908678,68.091228,18399,411385.187125,449346.548463,793334,21,2853,120446,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50257,132492,Transformer,32,North,Schneider,42.788963,39.616958,4.775346,-0.153694,66.890843,...,35.063877,98.801641,10925,840455.511290,312967.242818,477015,39,2525,485959,1
50316,112995,Transformer,27,North,ABB,86.270673,42.651624,3.341418,-0.432825,66.945977,...,38.818684,77.607569,23649,548483.280689,187927.422331,954812,27,1870,345560,1
50335,111730,Transformer,10,North,ABB,115.347291,86.970801,2.071722,0.092573,72.514706,...,55.158516,59.271887,27069,860922.207460,338904.947234,836587,26,8351,848970,1
50386,148871,Transformer,7,North,Siemens,88.686129,63.273769,14.379295,-0.056768,68.738921,...,2.790095,73.471472,65870,381724.356564,472330.317047,753431,9,4315,172169,1
50471,136884,Transformer,10,North,Schneider,89.786415,41.914915,3.310677,0.096573,68.739705,...,34.082242,56.218775,71609,91365.315839,36071.547202,936306,46,8841,542209,0

In [11]:
df[(df['asset_type'] == 'Substation') & (df['substation_region'] == 'North')]

,asset_id,asset_type,asset_age_years,substation_region,manufacturer,power_load_mw,load_utilization_pct,voltage_fluctuation_pct,frequency_deviation_hz,transformer_temperature_c,...,rainfall_mm,storm_risk_index,customers_served,estimated_revenue_loss,regulatory_penalty_cost,legacy_asset_code,grid_cluster_id,monitoring_batch_id,administrative_reference,grid_failure_flag
41,100041,Substation,2,North,Siemens,119.475923,34.862929,14.840384,0.343148,84.941710,...,21.061757,59.523453,50968,180583.717073,119069.879385,820059,32,8337,731589,1
44,100044,Substation,7,North,GE,88.619860,84.183437,4.071168,-0.281439,68.951913,...,46.288015,88.265909,5559,27997.603162,375810.637639,677994,32,3919,894760,1
246,100246,Substation,25,North,Hitachi,148.395062,56.343634,8.386688,0.059709,58.430722,...,20.318644,82.412017,71555,137141.845021,140418.580924,213609,25,4805,594479,1
267,100267,Substation,22,North,Hitachi,66.405448,66.832517,5.470706,0.121180,91.457129,...,22.667000,3.470406,85924,116491.473297,477557.633392,961108,40,3729,901545,0
296,100296,Substation,21,North,GE,48.722685,85.082285,11.181372,-0.476942,61.172264,...,12.393064,83.853824,96734,319036.024399,181359.669966,359998,33,2565,733284,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50437,104070,Substation,32,North,Hitachi,147.984634,91.558317,5.979593,0.236994,54.902875,...,15.187754,17.638913,27871,756858.331024,309635.085490,206194,45,3479,362195,0
50440,110074,Substation,8,North,Schneider,134.471558,37.447602,8.433427,0.223511,67.885309,...,7.486717,68.795225,52833,374714.752910,16643.899184,198685,1,4356,234472,0
50467,147767,Substation,17,North,Hitachi,134.614946,59.389353,7.234153,-0.049903,58.910657,...,55.308293,99.757494,44741,901455.555889,141706.013227,386469,48,2701,741936,1
50469,149184,Substation,32,North,Hitachi,54.367361,44.959011,13.937862,0.358098,64.010911,...,21.325468,9.641353,57247,174173.783657,468414.688768,998960,39,1403,564931,1
50498,129702,Substation,38,North,Schneider,107.990761,56.271493,11.471939,-0.038635,59.166827,...,12.043267,29.683645,23219,584071.166986,348812.469631,926912,20,1750,731213,0

In [13]:
df.sort_values(['substation_region', 'asset_type']).groupby(['substation_region', 'asset_type']).head(1)

,asset_id,asset_type,asset_age_years,substation_region,manufacturer,power_load_mw,load_utilization_pct,voltage_fluctuation_pct,frequency_deviation_hz,transformer_temperature_c,...,rainfall_mm,storm_risk_index,customers_served,estimated_revenue_loss,regulatory_penalty_cost,legacy_asset_code,grid_cluster_id,monitoring_batch_id,administrative_reference,grid_failure_flag
8,100008,Circuit Breaker,11,Central,Siemens,72.441944,93.926926,3.662961,0.055417,70.942524,...,26.922589,48.555847,67435,248250.046352,150470.475776,576618,34,5505,173664,1
5,100005,Substation,39,Central,ABB,68.130921,98.012108,11.072877,-0.269915,45.246638,...,62.389884,94.465944,33470,664948.376848,38153.004666,339535,48,1513,858842,1
1,100001,Switchgear,29,Central,Schneider,113.757291,70.553974,7.717056,0.374570,76.476670,...,13.164766,39.487362,47370,801405.346049,279753.231580,336586,37,5380,257421,0
59,100059,Transformer,36,Central,Siemens,81.401088,78.632849,10.832997,-0.332201,94.982215,...,59.292234,1.670105,19312,910407.238568,20790.262831,862792,6,3497,438474,0
0,100000,Transmission Line,39,Central,ABB,282.834500,81.260178,1.411161,-0.369930,66.340916,...,19.456628,66.896392,39815,586776.070558,340322.796883,139462,36,1711,810874,0
17,100017,Circuit Breaker,30,East,Schneider,29.554792,33.241823,14.509105,0.146232,66.721613,...,35.373478,34.844716,70231,907228.597634,385323.569561,807516,23,7199,292437,0
33,100033,Substation,9,East,Hitachi,130.134729,39.304653,12.770580,0.029796,61.461202,...,14.791554,12.224830,15447,961075.493122,45281.736394,277410,24,7151,466846,1
64,100064,Switchgear,14,East,ABB,126.395906,82.064868,9.870248,-0.395673,34.797700,...,20.427468,22.586365,33715,463876.545034,138608.743798,406081,10,8510,846514,1
16,100016,Transformer,24,East,ABB,91.398556,55.101891,4.320468,0.494831,73.492848,...,12.878435,44.519208,10609,451150.681723,303428.880807,164188,29,6663,976911,0
14,100014,Transmission Line,22,East,Siemens,84.436166,44.941654,5.780822,-0.280721,69.765005,...,19.984437,33.583882,37121,482506.937564,343819.920388,426229,18,4222,204324,1
10,100010,Circuit Breaker,24,North,Hitachi,90.921279,35.858270,13.519423,0.028750,50.287391,...,73.093613,3.002936,53492,259546.454412,8227.847825,414174,28,2224,469349,1
41,100041,Substation,2,North,Siemens,119.475923,34.862929,14.840384,0.343148,84.941710,...,21.061757,59.523453,50968,180583.717073,119069.879385,820059,32,8337,731589,1
61,100061,Switchgear,31,North,GE,116.638394,48.258618,12.186452,-0.262859,66.752238,...,28.598824,45.827199,4039,883819.405825,327725.319229,735868,23,1593,683956,0
6,100006,Transformer,19,North,GE,24.296135,66.411446,3.014399,-0.435844,44.241815,...,24.708504,10.976016,50575,852924.634858,264223.918831,457093,41,9871,753448,1
2,100002,Transmission Line,15,North,ABB,77.585841,39.118728,11.181348,0.024103,68.774685,...,32.955459,58.143304,25676,251440.743424,355793.399422,964465,36,7231,428171,1
4,100004,Circuit Breaker,21,South,Schneider,101.442960,84.967689,5.130973,-0.170869,91.874408,...,43.279001,88.483389,21706,20110.477241,464487.465960,800776,4,6848,491835,1
12,100012,Substation,24,South,Siemens,60.018380,31.399167,12.232784,0.305968,63.107741,...,41.344037,1.568520,11793,25123.787299,480020.030058,904475,31,5991,350491,1
18,100018,Switchgear,38,South,Hitachi,149.537138,85.434413,8.084807,-0.113660,90.337656,...,0.688879,89.785637,62602,900611.201920,216126.503320,616101,27,6959,989945,1
11,100011,Transformer,36,South,Siemens,142.697074,31.987168,10.602082,0.171140,57.294455,...,45.793661,83.894614,18697,181881.805508,150393.243641,324523,23,1510,378222,0
3,100003,Transmission Line,8,South,Schneider,84.918625,96.994550,4.052007,-0.162436,81.823217,...,38.933280,31.747796,46451,942296.677282,27470.270655,234440,36,8277,336795,0
19,100019,Circuit Breaker,2,West,GE,81.315766,80.345291,12.622313,-0.098128,64.240642,...,31.290343,49.416312,50856,31542.079657,394050.198861,917289,10,3087,273359,0
23,100023,Substation,22,West,ABB,52.360699,84.327660,12.727912,0.139051,84.837147,...,38.360182,65.213755,62056,103877.737131,33919.923967,418714,25,6199,727466,1
51,100051,Switchgear,2,West,GE,165.393514,98.300047,9.833610,0.440129,49.245767,...,30.636602,77.083008,86933,563066.814176,474266.742845,953290,15,6140,202500,1
22,100022,Transformer,12,West,GE,139.318427,54.722723,8.799411,0.425984,57.532855,...,12.744517,90.948469,23235,780284.363224,299075.691169,904912,31,8825,326619,1
43,100043,Transmission Line,28,West,Siemens,86.804692,74.367343,4.064222,-0.366841,82.107368,...,44.727943,72.993065,14639,436648.576468,6714.104780,209971,18,8706,614996,0

In [17]:
# group by grid_cluster_id, substation_region, asset_type and get the count of each group
df.groupby(['grid_cluster_id', 'substation_region', 'asset_type']).size()

grid_cluster_id  substation_region  asset_type
1                Central            Circuit Breaker      40
                                    Substation           37
                                    Switchgear           46
                                    Transformer          48
                                    Transmission Line    45
                                                         ..
49               West               Circuit Breaker      44
                                    Substation           39
                                    Switchgear           39
                                    Transformer          33
                                    Transmission Line    28
Length: 1225, dtype: int64

In [20]:
# Add grid_cluster_id, substation_region and asset_type to the breakdown
df.groupby(['grid_failure_flag', 'grid_cluster_id', 'substation_region', 'asset_type']).size()

grid_failure_flag  grid_cluster_id  substation_region  asset_type
0                  1                Central            Circuit Breaker      15
                                                       Substation           24
                                                       Switchgear           28
                                                       Transformer          38
                                                       Transmission Line    24
                                                                            ..
1                  49               West               Circuit Breaker      16
                                                       Substation           18
                                                       Switchgear           10
                                                       Transformer          17
                                                       Transmission Line    12
Length: 2450, dtype: int64

In [29]:
df[(df['substation_region'] == 'Central') & (df['grid_cluster_id'] == 1)].groupby(['grid_failure_flag', 'grid_cluster_id', 'substation_region', 'asset_type']).size()

grid_failure_flag  grid_cluster_id  substation_region  asset_type
0                  1                Central            Circuit Breaker      15
                                                       Substation           24
                                                       Switchgear           28
                                                       Transformer          38
                                                       Transmission Line    24
1                  1                Central            Circuit Breaker      25
                                                       Substation           13
                                                       Switchgear           18
                                                       Transformer          10
                                                       Transmission Line    21
dtype: int64

In [30]:
df[(df['grid_cluster_id'] == 1) & (df['substation_region'] == 'Central') & (df['asset_type'] == 'Substation')].sort_values('grid_failure_flag')[['grid_failure_flag'] + [col for col in df.columns if col != 'grid_failure_flag']]

,grid_failure_flag,asset_id,asset_type,asset_age_years,substation_region,manufacturer,power_load_mw,load_utilization_pct,voltage_fluctuation_pct,frequency_deviation_hz,...,wind_speed_kmh,rainfall_mm,storm_risk_index,customers_served,estimated_revenue_loss,regulatory_penalty_cost,legacy_asset_code,grid_cluster_id,monitoring_batch_id,administrative_reference
1817,0,101817,Substation,2,Central,Siemens,137.290111,49.109194,13.253766,0.280693,...,104.452239,26.683577,11.933898,24632,447215.931180,50933.474746,906963,1,3411,898879
3654,0,103654,Substation,8,Central,GE,104.013089,68.877418,14.637653,-0.152122,...,113.016075,73.604762,50.257158,23481,123972.418721,62293.148340,789234,1,7522,990036
6837,0,106837,Substation,13,Central,Siemens,79.086336,57.387544,4.848620,0.230141,...,46.396389,17.315097,73.056626,91443,307807.316901,170880.613486,763165,1,6969,319613
6318,0,106318,Substation,24,Central,GE,131.710691,39.390280,9.684441,-0.162467,...,61.089605,96.699229,53.168273,12393,954339.748172,100740.823580,411136,1,3595,379780
7364,0,107364,Substation,21,Central,ABB,50.476477,82.085016,0.843423,0.119934,...,114.408382,4.249943,95.156660,44662,532386.183202,403472.964966,180249,1,1343,846978
9910,0,109910,Substation,39,Central,Hitachi,145.857678,52.355657,4.756644,-0.511169,...,39.676548,6.677038,96.913606,75104,716852.887521,240275.697038,331516,1,8940,624518
16462,0,116462,Substation,34,Central,Hitachi,82.097001,41.090156,12.412409,0.216615,...,51.309347,34.583792,33.075703,34016,827320.718697,324638.738986,216384,1,6053,911534
12759,0,112759,Substation,38,Central,Schneider,70.674551,57.384728,14.042888,-0.196244,...,98.344492,9.339343,7.892646,7651,56300.120548,121784.843827,251908,1,5487,395907
17604,0,117604,Substation,16,Central,Hitachi,31.333096,96.828534,14.123429,-0.087036,...,47.326284,43.538717,23.553344,6744,873287.681607,282649.325819,959180,1,2822,419586
26266,0,126266,Substation,4,Central,Schneider,149.980037,57.204274,9.618835,-0.086893,...,72.867715,50.608595,51.947343,23848,216634.420105,337257.186219,349696,1,7662,851181
24310,0,124310,Substation,36,Central,Hitachi,223.831594,77.125083,1.859270,0.077469,...,56.725246,9.012655,38.178523,46480,482696.030619,57827.058210,982324,1,7530,779630
25482,0,125482,Substation,17,Central,Hitachi,96.769768,51.996861,3.287267,-0.458015,...,89.820070,13.490634,24.826957,34052,631873.930404,495469.318514,257303,1,5051,369581
23589,0,123589,Substation,30,Central,GE,93.437515,45.068405,14.054031,0.325673,...,48.959279,15.172865,83.028717,42309,131852.730324,82359.282367,129986,1,2896,371254
23412,0,123412,Substation,13,Central,Hitachi,78.695442,80.505418,9.144550,-0.456534,...,118.433634,26.525260,25.171624,9247,620484.251711,438324.553136,782453,1,3020,358119
21625,0,121625,Substation,2,Central,GE,63.294818,82.816481,10.129956,0.002681,...,38.495480,36.536580,58.727069,86951,998424.126029,370729.311434,308083,1,4967,957846
19949,0,119949,Substation,20,Central,ABB,156.443066,60.538137,12.745564,0.081391,...,49.248343,17.328025,20.090514,85338,648283.411479,218375.303578,394839,1,7022,586743
44492,0,144492,Substation,2,Central,Hitachi,77.364134,85.450570,9.271270,-0.162160,...,13.332207,10.735965,7.071183,31622,992543.790561,226794.076375,727619,1,5553,218077
43526,0,143526,Substation,13,Central,Siemens,37.346932,82.320853,8.783873,0.219849,...,24.005996,9.326760,47.870702,88426,372238.509236,87958.500124,970351,1,7751,674676
33374,0,133374,Substation,11,Central,GE,176.609394,31.052256,9.783575,0.000485,...,6.118397,48.275289,60.079579,69687,140592.188957,51434.509577,654091,1,8127,745147
40950,0,140950,Substation,19,Central,Siemens,53.573711,78.451760,14.646244,0.216453,...,105.934494,28.620576,14.694671,92115,803851.620837,39677.170525,533595,1,8351,668436
25604,0,125604,Substation,26,Central,Siemens,89.808413,81.348728,3.611645,0.154386,...,60.451919,12.195596,18.275751,11918,227595.297643,115767.913273,218409,1,8482,823025
49617,0,149617,Substation,39,Central,Schneider,125.624039,58.445466,4.418585,0.061723,...,26.235580,14.513403,81.627846,99988,589675.608185,437507.707310,373044,1,9139,117365
45457,0,145457,Substation,26,Central,GE,43.805795,84.389260,0.163854,-0.205186,...,34.393502,24.802954,28.205724,27146,81983.413389,255271.417543,314247,1,1911,605322
44746,0,144746,Substation,3,Central,GE,78.350750,96.851048,4.357795,-0.524745,...,61.966534,58.806382,49.432608,68688,313124.069775,158826.916790,380096,1,4645,700851
19738,1,119738,Substation,36,Central,ABB,60.015887,63.193584,14.365191,0.257251,...,64.410732,32.321496,29.308648,85048,927332.970401,37081.327439,462149,1,4667,353956
15543,1,115543,Substation,2,Central,Siemens,85.997121,85.291782,7.832876,-0.431699,...,95.442886,30.523735,23.269815,21999,370939.726010,11211.475476,617830,1,2196,121937
13530,1,113530,Substation,3,Central,GE,97.171443,76.952108,14.837974,-0.089123,...,39.617403,15.542938,91.908631,44746,343212.934584,162116.451723,501523,1,1999,891334
14792,1,114792,Substation,32,Central,ABB,103.474744,74.882241,8.425071,0.124754,...,28.660669,15.105635,64.799446,26450,936767.743208,80756.874653,539613,1,1277,229537
25325,1,125325,Substation,9,Central,Schneider,146.489527,98.233520,6.094512,-0.288640,...,46.538892,8.711770,23.533204,24370,443422.280996,330827.262231,772955,1,3254,142667
11627,1,111627,Substation,27,Central,Hitachi,174.037349,54.287944,11.288571,-0.003533,...,119.173688,55.750038,32.268064,40264,744288.625334,170073.651491,409710,1,5315,369995
3311,1,103311,Substation,7,Central,ABB,168.760348,58.937548,5.085824,-0.542236,...,114.802064,35.087496,82.435947,65125,176802.751767,306801.357896,315257,1,1795,349976
1556,1,101556,Substation,33,Central,Schneider,17.534185,47.118506,8.353746,-0.023595,...,3.385042,7.187631,72.420117,30519,611365.844117,59161.172037,903776,1,5248,879158
41706,1,141706,Substation,9,Central,Schneider,143.571979,44.103901,13.061543,0.021654,...,31.375193,15.743026,46.562351,15108,723135.000434,478265.625163,850353,1,6648,975711
42827,1,142827,Substation,9,Central,GE,119.784903,73.432244,2.762214,0.359496,...,46.200478,24.862348,78.300291,8480,852594.750081,138536.408563,861825,1,5494,795579
22133,1,122133,Substation,13,Central,ABB,37.825900,48.205457,14.027421,0.710382,...,92.228573,38.571064,33.647614,75144,101152.163507,258139.084815,701749,1,3741,298756
45812,1,145812,Substation,37,Central,Schneider,28.866417,83.121029,6.441703,-0.304198,...,107.246336,20.357215,85.270142,14646,931971.407400,384560.624840,571791,1,4914,326453
48601,1,148601,Substation,9,Central,Siemens,106.277814,97.162153,1.686324,-0.161460,...,109.521264,12.809363,89.649435,91554,661004.592104,489768.658699,178042,1,9296,435262